### ISSUE TITLE
Errors on init

### ISSUE THREAD

**Issue by delaneyj** [evilkiwi/embed#1] opened 2021-08-02 18:07 UTC
**Describe the bug**

**To Reproduce**
1. Create 2 vite apps.  C/P the host/remote example but on (8888 host and 3000 client).
2. Modified example works but has errors (most likely when the iframe is still initializing)

**Expected behavior**
Don't throw Errors unless is actually past the setup timeout.  This might not be the problem but causes issues for automated testing when the browser starts with errors but is in a working state after less than a second.

**Screenshots**
![image](https://user-images.githubusercontent.com/438252/127904736-7c0e1066-4aed-4001-87c3-a92dfbbbd75a.png)

**Comment by devlsh** [comment] 2021-08-03 00:19
I'll take a look - I don't think that's the problem, it looks like the library isn't realizing the iFrame is sandboxed and isn't allowing same-origin (Which is why the child has an origin of `'null'`)

I thought this should work, but there's likely an edge case I'm not aware of. Could you enable debug on both host & client (`useEmbed({ debug: true })`) and post the console after enabling it please? Or if you let me know what modifications to make to the example apps to reproduce the issue.

**Comment by delaneyj** [comment] 2021-08-04 16:35
From what I understand being on a different port means its a different origin, unless I've misread.  Turning on `debug:true` unfortunately doesn't give any extra information.  I'm going to try your example locally as slowly build up an example.

**Comment by delaneyj** [comment] 2021-08-05 15:12
Oddly, I get the same errors trying to run your example

![image](https://user-images.githubusercontent.com/438252/128374557-762208b2-7ee1-4c8a-997e-3f24dfc6d6e2.png)

**Comment by devlsh** [comment] 2021-08-06 05:39
Interesting - which version of Chrome and Vue are you using?

**Comment by devlsh** [comment] 2021-10-19 09:05
Closing - think I found the culprit, which was an edge-case where the iFrame contentWindow would be null as I was purely listening to the DOM being available. Switched to listening for the load event and seems good now.

**Closed as completed by devlsh** 2021-10-19 09:05 UTC
Labels: bug
